import {
  BarChart3,
  Building2,
  CalendarCheck2,
  CalendarDays,
  FileArchive,
  FileBarChart2,
  FileText,
  HandCoins,
  Hospital,
  KeyRound,
  Layers3,
  ReceiptText,
  Share2,
  ShieldCheck,
  Stethoscope,
  FolderCog,
  Settings2,
  UsersRound,
} from 'lucide-react'

export const navSections = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: BarChart3,
    path: '/dashboard',
    requiredRoles: ['ADMIN', 'DOCTOR', 'RECEPCION'],
    items: [],
  },
  {
    id: 'clinica',
    label: 'Clínica',
    icon: Stethoscope,
    items: [
      { id: 'patients', path: '/patients', label: 'Pacientes', icon: UsersRound, requiredPermission: 'PATIENTS_READ' },
      { id: 'appointments', path: '/appointments', label: 'Agenda de Citas', icon: CalendarDays, requiredPermission: 'APPOINTMENTS_READ' },
      { id: 'internal-referrals', path: '/clinical-sharing/internal-referrals', label: 'Pacientes Remitidos', icon: CalendarCheck2, requiredPermission: 'CLINICAL_SHARE_READ' },
      { id: 'consultations', path: '/consultations', label: 'Consultas', icon: FileText, requiredPermission: 'PATIENTS_READ', requiredRoles: ['ADMIN', 'DOCTOR'] },
      { id: 'clinical-sharing', path: '/clinical-sharing', label: 'Interconsultas', icon: Share2, requiredPermission: 'CLINICAL_SHARE_READ' },
      { id: 'specialties', path: '/admin/specialties', label: 'Especialidades', icon: Stethoscope, requiredPermission: 'ACCESS_MANAGE' },
    ],
  },
  {
    id: 'comercial',
    label: 'Comercial',
    icon: HandCoins,
    items: [
      { id: 'services', path: '/admin/services', label: 'Servicios', icon: ReceiptText, requiredPermission: 'BILLING_WRITE' },
      { id: 'invoices', path: '/invoices', label: 'Facturación', icon: ReceiptText, requiredPermission: 'BILLING_READ' },
      { id: 'payments', path: '/payments', label: 'Pagos', icon: HandCoins, requiredPermission: 'BILLING_READ' },
      { id: 'cash-register', path: '/cash-register', label: 'Caja', icon: HandCoins, requiredPermission: 'BILLING_READ' },
    ],
  },
  {
    id: 'plataforma',
    label: 'Plataforma',
    icon: Settings2,
    items: [
      { id: 'file-types', path: '/admin/file-types', label: 'Tipos de Archivo', icon: FileArchive, requiredPermission: 'ACCESS_MANAGE' },
      { id: 'storage-providers', path: '/admin/storage-providers', label: 'Storage Providers', icon: Hospital, requiredPermission: 'ACCESS_MANAGE' },
      { id: 'invoice-status', path: '/admin/invoice-status', label: 'Estados Factura', icon: ReceiptText, requiredPermission: 'ACCESS_MANAGE' },
      { id: 'payment-methods', path: '/admin/payment-methods', label: 'Métodos de Pago', icon: HandCoins, requiredPermission: 'ACCESS_MANAGE' },
      { id: 'payment-status', path: '/admin/payment-status', label: 'Estados de Pago', icon: ShieldCheck, requiredPermission: 'ACCESS_MANAGE' },
      { id: 'share-types', path: '/admin/share-types', label: 'Tipos de Compartición', icon: Layers3, requiredPermission: 'ACCESS_MANAGE' },
      { id: 'share-standards', path: '/admin/share-standards', label: 'Estándares', icon: ShieldCheck, requiredPermission: 'ACCESS_MANAGE' },
      { id: 'appointment-types', path: '/admin/appointment-types', label: 'Tipos de Cita', icon: CalendarCheck2, requiredPermission: 'ACCESS_MANAGE' },
      { id: 'appointment-status', path: '/admin/appointment-status', label: 'Estados de Cita', icon: Layers3, requiredPermission: 'ACCESS_MANAGE' },
    ],
  },
  {
    id: 'seguridad-acceso',
    label: 'Seguridad y Acceso',
    icon: FolderCog,
    requiredPermissions: ['TENANTS_MANAGE', 'USERS_MANAGE', 'ACCESS_MANAGE'],
    requiredRoles: ['ADMIN'],
    items: [
      { id: 'tenants', path: '/tenants', label: 'Tenants', icon: Building2, requiredPermission: 'TENANTS_MANAGE' },
      { id: 'employees', path: '/employees', label: 'Empleados', icon: KeyRound, requiredPermission: 'USERS_MANAGE' },
      { id: 'roles', path: '/roles', label: 'Roles', icon: ShieldCheck, requiredPermission: 'ACCESS_MANAGE' },
    ],
  },
  {
    id: 'reportes',
    label: 'Reportes',
    icon: FileBarChart2,
    items: [{ id: 'reports', path: '/reports', label: 'Reportes', icon: FileBarChart2, requiredPermission: 'REPORTS_READ' }],
  },
]
