export const tenantsCatalogConfig = {
  entity: 'tenants',
  title: 'Tenants',
  description: 'Administración de clínicas registradas en la plataforma',
  searchPlaceholder: 'Buscar por clinic code, NIT o razón social',
  pageSize: 10,
  sortBy: 'created_at',
  sortDir: 'desc',
  columns: [
    {
      key: 'clinic_code',
      label: 'Clinic Code',
    },
    {
      key: 'razon_social',
      label: 'Razón Social',
    },
    {
      key: 'nit',
      label: 'NIT',
    },
    {
      key: 'email',
      label: 'Email',
      render: (value) => value || 'N/A',
    },
    {
      key: 'estatus',
      label: 'Estado',
      render: (value) => (Number(value) === 1 ? 'Activo' : 'Inactivo'),
      variant: 'status-badge',
    },
  ],
  formFields: [
    {
      name: 'nombre_comercial',
      label: 'Nombre Comercial',
      required: true,
      requiredMessage: 'Nombre Comercial es obligatorio',
      placeholder: 'Clínica Demo',
      fullWidth: true,
      regex: "^[\\p{L}\\p{N}\\s.,'()\\-_/&#+:;°]+$",
      regexMessage: 'Nombre Comercial inválido',
    },
    {
      name: 'nit',
      label: 'NIT',
      required: true,
      requiredMessage: 'NIT es obligatorio',
      placeholder: '1234567-8',
      regex: '^[A-Za-z0-9]+$',
      regexMessage: 'NIT inválido (solo letras y números)',
    },
    {
      name: 'razon_social',
      label: 'Razón Social',
      required: true,
      requiredMessage: 'Razón Social es obligatoria',
      placeholder: 'Clínica Demo, S.A.',
      regex: "^[\\p{L}\\p{N}\\s.,'()\\-_/&#+:;°]+$",
      regexMessage: 'Razón Social inválida',
    },
    {
      name: 'telefono',
      label: 'Teléfono',
      required: true,
      requiredMessage: 'Teléfono es obligatorio',
      placeholder: '5555-0000',
      regex: '^[0-9]+$',
      regexMessage: 'Teléfono inválido (solo números)',
    },
    {
      name: 'email',
      label: 'Email',
      type: 'email',
      placeholder: 'contacto@clinicademo.com',
      regex: '^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$',
      regexMessage: 'Email inválido',
    },
    {
      name: 'direccion',
      label: 'Dirección',
      required: true,
      requiredMessage: 'Dirección es obligatoria',
      placeholder: 'Zona 10, Ciudad',
      fullWidth: true,
      regex: "^[\\p{L}\\p{N}\\s.,'()\\-_/&#+:;°]+$",
      regexMessage: 'Dirección inválida',
    },
  ],
  messages: {
    created: 'Tenant creado correctamente',
    updated: 'Tenant actualizado correctamente',
    deleted: 'Tenant inactivado correctamente',
  },
}
